quarkus:
  live-reload:
    instrumentation: true

  hibernate-orm:
    active: true
    log:
      sql: true
  flyway:
    migrate-at-start: true

quarkus.hibernate-orm.active=true
quarkus.hibernate-orm.log.sql=true
quarkus.flyway.migrate-at-start=true

#link to yhfinance API:
#  https://financeapi.net/