quarkus:
  datasource:
    username: "screener"
    password: "password"
    jdbc:
      url: "jdbc:postgresql://localhost:5432/screener"
  flyway:
    active: true
  hibernate-orm:
    active: true
    scripts:
      generation: "validate"